/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const FlashCardsLazyImport = createFileRoute('/flash-cards')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const FlashCardsLazyRoute = FlashCardsLazyImport.update({
  path: '/flash-cards',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/flash-cards.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/flash-cards': {
      id: '/flash-cards'
      path: '/flash-cards'
      fullPath: '/flash-cards'
      preLoaderRoute: typeof FlashCardsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FlashCardsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/flash-cards"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/flash-cards": {
      "filePath": "flash-cards.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
